# training_data_generator.py
import json

def append_to_training_set(niche, problem, scraped_context, ideal_strategy_output):
    """
    Appends successful, high-quality strategy runs to a fine-tuning dataset.
    Run this when a strategy generated by the AI is manually approved as "Gold Standard".
    """
    training_file = "neurostrat_finetune_v1.jsonl"
    
    # Structure required for fine-tuning Chat models
    training_example = {
        "messages": [
            {
                "role": "system", 
                "content": "You are NeuroStrat, a data-driven strategy AI. Output ruthless, highly specific JSON playbooks."
            },
            {
                "role": "user", 
                "content": f"Niche: {niche}. Problem: {problem}. Live Context: {json.dumps(scraped_context)}"
            },
            {
                "role": "assistant", 
                "content": json.dumps(ideal_strategy_output) # The gold-standard response
            }
        ]
    }
    
    with open(training_file, "a") as f:
        f.write(json.dumps(training_example) + "\n")
        
    print(f"Added training node. Current dataset size: {sum(1 for _ in open(training_file))}")

# Example Execution:
# append_to_training_set(niche, problem, social_data, validated_json_strategy)